const chapterItems = [
  {
    chapterId: 1,
    lessonId: 1,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/welcomeimage1661254149_256.jpg",
    mainText: "الترحيب بالاخرين",
    subText: "تعلم التحية عند مقابلة الأشخاص",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 1,
    lessonId: 2,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/davidcover1661254508_256.jpg",
    mainText: "تقديم نفسك",
    subText: "قل اسمك",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 1,
    lessonId: 3,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/sogreat1661259325_256.jpg",
    mainText: "توديع الغير",
    subText: "كيف تودع الاخرين",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 1,
    lessonId: 4,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/european-man-woman-casual-wear-standing-back-back-with-arms-crossed-isolated-colorful-wall_171337-51292.jpg",
    mainText: "طلب القهوة",
    subText: "اطلب قهوتك ببساطة",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 1,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 2,
    lessonId: 1,
    completed: false,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/jack.jpeg",
    mainText: "وصف الجنسية",
    subText: "السؤال عن جنسية الآخرين والتعريف بجنسيتك",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 2,
    lessonId: 2,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/davidcover1661254508_256.jpg",
    mainText: "قول أين تعيش",
    subText: "تحدث عن المكان الذي تعيش فيه",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 2,
    lessonId: 3,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/sogreat1661259325_256.jpg",
    mainText: "إعطاء جنسيتك",
    subText: "تعلم كيفية القول من أي دولة أنت",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 2,
    lessonId: 4,
    completed: false,
    imgSrc:
      "https://alsallum.s3.eu-north-1.amazonaws.com/european-man-woman-casual-wear-standing-back-back-with-arms-crossed-isolated-colorful-wall_171337-51292.jpg",
    mainText: "إنهاء المحادثة",
    subText: "تعلم كيفية إنهاء المحادثة",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 2,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 3,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الفعل 'to be' (المفرد)",
    subText: "ضمائر الفاعل المفردة والفعل 'to be'",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 3,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الفعل 'to be' (الجمع)",
    subText: "ضمائر الفاعل الجمع والفعل 'to be'",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 3,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الأفعال العادية",
    subText: "تحدث عن اللغات التي نعرفها باستخدام الفعل 'to speak'",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 3,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "أشكال الفعل المنفية",
    subText: "كون صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 3,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 4,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الفعل 'to be' (المفرد)",
    subText: "ضمائر الفاعل المفردة والفعل 'to be'",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 4,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الفعل 'to be' (الجمع)",
    subText: "ضمائر الفاعل الجمع والفعل 'to be'",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 4,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الأفعال العادية",
    subText: "تحدث عن اللغات التي نعرفها باستخدام الفعل 'to speak'",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 4,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "أشكال الفعل المنفية",
    subText: "كون صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 4,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 5,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الفعل 'to be' (المفرد)",
    subText: "ضمائر الفاعل المفردة والفعل 'to be'",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 5,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الفعل 'to be' (الجمع)",
    subText: "ضمائر الفاعل الجمع والفعل 'to be'",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 5,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الأفعال العادية",
    subText: "تحدث عن اللغات التي نعرفها باستخدام الفعل 'to speak'",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 5,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "أشكال الفعل المنفية",
    subText: "كون صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 5,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 6,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "الفعل 'to be' (المفرد)",
    subText: "ضمائر الفاعل المفردة والفعل 'to be'",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 6,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الفعل 'to be' (الجمع)",
    subText: "ضمائر الفاعل الجمع والفعل 'to be'",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 6,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/globe.webp",
    mainText: "الأفعال العادية",
    subText: "تحدث عن اللغات التي نعرفها باستخدام الفعل 'to speak'",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 6,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/microscope.webp",
    mainText: "أشكال الفعل المنفية",
    subText: "كون صيغة النفي للأفعال العادية في الزمن الحاضر البسيط",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 6,
    lessonId: 5,
    type: "checkpoint",
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/Diamond.png",
    mainText: "نقطة التحقق",
    subText: "اختبر مهاراتك للوصول إلى الفصل التالي",
    url: "lesson/lesson",
    set: "set5",
  },
  {
    chapterId: 7,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 7,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 7,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 7,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 7,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "أفعال الحركة",
    subText: "استخدام أفعال الحركة في الحديث اليومي",
    url: "lesson/lesson",
    set: "set4",
  },

  // ... (other lessons in Chapter 7)
  {
    chapterId: 8,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 8,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 8,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 8,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 8,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "استخدام الشرط",
    subText: "تعلم استخدام العبارات الشرطية",
    url: "lesson/lesson",
    set: "set5",
  },
  // ... (other lessons in Chapter 8)

  // Add more chapters for Advanced C1 (Chapters 9 and 10)
  {
    chapterId: 9,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 9,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 9,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 9,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 9,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 9,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/pencil.webp",
    mainText: "التعابير الاصطلاحية",
    subText: "فهم واستخدام التعابير الاصطلاحية",
    url: "lesson/lesson",
    set: "set5",
  },
  // ... (other lessons in Chapter 9)
  {
    chapterId: 10,
    lessonId: 1,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set1",
  },
  {
    chapterId: 10,
    lessonId: 2,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set2",
  },
  {
    chapterId: 10,
    lessonId: 3,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set3",
  },
  {
    chapterId: 10,
    lessonId: 4,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set4",
  },
  {
    chapterId: 10,
    lessonId: 5,
    imgSrc: "https://alsallum.s3.eu-north-1.amazonaws.com/blackboard.webp",
    mainText: "الخطابات الرسمية",
    subText: "كيفية كتابة خطابات رسمية",
    url: "lesson/lesson",
    set: "set5",
  },
];

export default chapterItems;
